### ISSUE TITLE
Compiling on ARM architecture 

### ISSUE THREAD

**Issue by PMuchina** [UCLA-VAST/minimap2-acceleration#5]
I am working on a jetson nano platform (ARM). I get this error while compiling

cc: error: unrecognized command line option ‘-msse2’
make: *** [Makefile:51: ksw2_ll_sse.o] Error 1

**Comment by dotkrnl** [comment]
The [original Minimap2](https://github.com/lh3/minimap2) uses the SSE2 instruction set, so does the test data generator in this project.  You may want to run the generator on an x86 computer to generate the data and copy the data to your ARM platform.

Note that we did not test on Jetson and I am not sure if the CUDA code works.  The CPU acceleration may not work either because it was optimized for Intel CPU.
